pub mod pen {
    use windows::Win32::UI::Input::Pointer::*;

    // ugly workaround until bitwise operation in win_rs is supported in const context
    pub const PEN_HOVER: POINTER_FLAGS = POINTER_FLAGS { 0: (POINTER_FLAG_PRIMARY.0 | POINTER_FLAG_INRANGE.0 | POINTER_FLAG_UPDATE.0) };
    pub const PEN_DOWN: POINTER_FLAGS = POINTER_FLAGS { 0: (POINTER_FLAG_PRIMARY.0 | POINTER_FLAG_INRANGE.0 | POINTER_FLAG_INCONTACT.0 | POINTER_FLAG_DOWN.0) };
    pub const PEN_CONTACT: POINTER_FLAGS = POINTER_FLAGS { 0: (POINTER_FLAG_PRIMARY.0 | POINTER_FLAG_INRANGE.0 | POINTER_FLAG_INCONTACT.0 | POINTER_FLAG_UPDATE.0) };
    pub const PEN_UP: POINTER_FLAGS = POINTER_FLAGS { 0: (POINTER_FLAG_PRIMARY.0 | POINTER_FLAG_INRANGE.0 | POINTER_FLAG_UP.0) };
    pub const PEN_ENDHOVER: POINTER_FLAGS = POINTER_FLAGS { 0: (POINTER_FLAG_PRIMARY.0 | POINTER_FLAG_UPDATE.0) };
}

pub mod touch {
    use windows::Win32::UI::Input::Pointer::*;

    pub const TOUCH_UP: POINTER_FLAGS = POINTER_FLAG_UP;
    pub const TOUCH_DOWN: POINTER_FLAGS = POINTER_FLAGS { 0: (POINTER_FLAG_DOWN.0 | POINTER_FLAG_INRANGE.0 | POINTER_FLAG_INCONTACT.0) };
    pub const TOUCH_CONTACT: POINTER_FLAGS = POINTER_FLAGS { 0: (POINTER_FLAG_UPDATE.0 | POINTER_FLAG_INRANGE.0 | POINTER_FLAG_INCONTACT.0) };
}

